# nonk8s
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: prom-aggregation-gateway
build:
  artifacts:
    - image: prom-aggregation-gateway
      custom:
        buildCommand: EARTHLY_DISABLE_REMOTE_REGISTRY_PROXY=true ./earthly +build-image --version=$IMAGE_TAG --image_name=$IMAGE_REPO --no-satellite
  tagPolicy:
    customTemplate:
      template: dev
manifests:
  helm:
    releases:
      - name: prom-aggregation-gateway
        chartPath: ./charts/prom-aggregation-gateway
        createNamespace: true
        setValues:
          controller.image.repository: prom-aggregation-gateway
          controller.image.tag: dev
          podMonitor.create: false
          serviceMonitor.create: false
