controller:
  image:
    repository: ghcr.io/zapier/prom-aggregation-gateway
    tag: latest

  replicaCount: 1

  type: Deployment

podMonitor:
  create: true

service:
  create: true
  annotations: {}
  type: LoadBalancer
  port: 8080
  nodePort: 12345

serviceMonitor:
  create: true
