apiVersion: apps/v1
kind: {{ .Values.controller.type }}
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "prom-aggregation-gateway.labels" . | nindent 4 }}
    {{- if .Values.controller.labels }}
    {{- toYaml .Values.controller.labels | nindent 4 }}
    {{- end }}

spec:
  selector:
    matchLabels:
      {{- include "prom-aggregation-gateway.selectorLabels" . | nindent 6 }}
  {{- if eq .Values.controller.type "Deployment" }}
  replicas: {{ .Values.controller.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "prom-aggregation-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: prom-aggregation-gateway
          image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}
          args:
            - --listen=":8080"
            - --metricsListen=":8888"
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8888
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
