name: go ci
on: 
  pull_request:
    paths:
      - '.github/workflows/on_pull_request_go.yaml'
      - 'Earthfile'
      - '*/**.go'
      - '*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  ci-golang:
    runs-on: ubuntu-22.04
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.6.30

      - uses: actions/checkout@v3

      - run: earthly +ci-golang
